// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_TJ0sWivMljruhPHGzIT6o0vLfyN3BY',
    appId: '1:1078552236233:web:54d3e110cee97d13d73d18',
    messagingSenderId: '1078552236233',
    projectId: 'aqua-101',
    authDomain: 'aqua-101.firebaseapp.com',
    databaseURL: 'https://aqua-101-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aqua-101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuxssitFkpvhLcW4UUiimn7x_egcey1sU',
    appId: '1:1078552236233:android:77d7db5413b64300d73d18',
    messagingSenderId: '1078552236233',
    projectId: 'aqua-101',
    databaseURL: 'https://aqua-101-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aqua-101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxzu_w98vPSjmatij0b_Kx7inglKPcpc',
    appId: '1:1078552236233:ios:74e4758fcf7a1392d73d18',
    messagingSenderId: '1078552236233',
    projectId: 'aqua-101',
    databaseURL: 'https://aqua-101-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aqua-101.appspot.com',
    iosBundleId: 'com.example.aqua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdxzu_w98vPSjmatij0b_Kx7inglKPcpc',
    appId: '1:1078552236233:ios:e47b1bafb37a32c8d73d18',
    messagingSenderId: '1078552236233',
    projectId: 'aqua-101',
    databaseURL: 'https://aqua-101-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aqua-101.appspot.com',
    iosBundleId: 'com.example.aqua.RunnerTests',
  );
}
